config/routes.rb
Dmap::Application.routes.draw do
  
  get "home/index"
  get "home/about"

  resources :tenures
  resources :people
  resources :positions
  resources :bodies
  resources :agencies
  resources :jurisdictions

  root :to => "home#index"
end

app/models/body.rb
class Body
  include Mongoid::Document
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController
  # GET /bodies
  # GET /bodies.json
  def index
    @bodies = Body.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bodies }
    end
  end

  # GET /bodies/1
  # GET /bodies/1.json
  def show
    @body = Body.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @body }
    end
  end

  # GET /bodies/new
  # GET /bodies/new.json
  def new
    @body = Body.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @body }
    end
  end

  # GET /bodies/1/edit
  def edit
    @body = Body.find(params[:id])
  end

  # POST /bodies
  # POST /bodies.json
  def create
    @body = Body.new(params[:body])

    respond_to do |format|
      if @body.save
        format.html { redirect_to @body, notice: 'Body was successfully created.' }
        format.json { render json: @body, status: :created, location: @body }
      else
        format.html { render action: "new" }
        format.json { render json: @body.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bodies/1
  # PUT /bodies/1.json
  def update
    @body = Body.find(params[:id])

    respond_to do |format|
      if @body.update_attributes(params[:body])
        format.html { redirect_to @body, notice: 'Body was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @body.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bodies/1
  # DELETE /bodies/1.json
  def destroy
    @body = Body.find(params[:id])
    @body.destroy

    respond_to do |format|
      format.html { redirect_to bodies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/views/bodies/_form.html.erb
<%= form_for(@body) do |f| %>
  <% if @body.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@body.errors.count, "error") %> prohibited this body from being saved:</h2>

      <ul>
      <% @body.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bodies/edit.html.erb
<h1>Editing body</h1>

<%= render 'form' %>

<%= link_to 'Show', @body %> |
<%= link_to 'Back', bodies_path %>

app/views/bodies/index.html.erb
<h1>Listing bodies</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bodies.each do |body| %>
  <tr>
    <td><%= link_to 'Show', body %></td>
    <td><%= link_to 'Edit', edit_body_path(body) %></td>
    <td><%= link_to 'Destroy', body, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Body', new_body_path %>

app/views/bodies/new.html.erb
<h1>New body</h1>

<%= render 'form' %>

<%= link_to 'Back', bodies_path %>

app/views/bodies/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_body_path(@body) %> |
<%= link_to 'Back', bodies_path %>